[workspace]
members = [
    "crates/mole_core",
    "crates/mole_rollback",
    "crates/mole_replay",
    "crates/mole_transport",
    "crates/mole_runtime",
    "crates/mole_input",
    "crates/mole_signaling",
    "crates/mole_frame_data",
    "crates/mole_ledger",
    "crates/mole_devtool",
    "crates/mole_cli",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
