"""Generate Rust Falcon ECB tables from extracted Melee action samples."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any

try:
    from tools.falcon_ecb_mapping import (
        MOTION_STATE_ACTION_MAP,
        UNMAPPED_DERIVED_MOTION_STATES,
        sampled_action_ids,
    )
except ModuleNotFoundError:  # pragma: no cover - direct script execution path
    from falcon_ecb_mapping import (  # type: ignore
        MOTION_STATE_ACTION_MAP,
        UNMAPPED_DERIVED_MOTION_STATES,
        sampled_action_ids,
    )

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = PROJECT_ROOT / "resources" / "melee" / "extracted" / "captain_falcon_action_ecb_samples.json"
DEFAULT_OUTPUT = PROJECT_ROOT / "crates" / "mole_core" / "src" / "generated" / "falcon_ecb.rs"
DEFAULT_COVERAGE_JSON = PROJECT_ROOT / "docs" / "state_graphs" / "parity_reports" / "falcon_ecb_coverage.json"


def render_generated_rust(samples: dict[str, Any]) -> str:
    actions = {
        int(action["action_state_id"]): action
        for action in samples.get("actions", [])
        if isinstance(action, dict)
    }
    mapped_action_ids = [
        action_id for action_id in sampled_action_ids() if action_id in actions
    ]

    lines: list[str] = [
        "// @generated by tools/generate_falcon_ecb_rust.py; do not edit by hand.",
        "use super::{MotionState, Vec2};",
        "use crate::collision::EcbDiamond;",
        "",
        "#[allow(dead_code)]",
        f"pub(crate) const FALCON_ECB_MAPPED_ACTION_COUNT: usize = {len(mapped_action_ids)};",
        "",
    ]

    for action_id in mapped_action_ids:
        action = actions[action_id]
        frames = action.get("frames", [])
        source_name = str(action.get("name") or action.get("figatree_root") or "")
        lines.append(f"// action {action_id}: {source_name}")
        lines.append(
            f"const FALCON_ECB_ACTION_{action_id}: [EcbDiamond; {len(frames)}] = ["
        )
        for frame in frames:
            lines.append(f"    {render_ecb(frame)},")
        lines.append("];")
        lines.append("")

    lines.append("pub(crate) fn falcon_ecb_samples_for_motion_state(")
    lines.append("    motion_state: MotionState,")
    lines.append(") -> Option<&'static [EcbDiamond]> {")
    lines.append("    match motion_state {")
    for state, action_id in MOTION_STATE_ACTION_MAP:
        if action_id in actions:
            lines.append(
                f"        MotionState::{state} => Some(&FALCON_ECB_ACTION_{action_id}),"
            )
    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#[allow(dead_code)]")
    if UNMAPPED_DERIVED_MOTION_STATES:
        lines.append("pub(crate) const FALCON_ECB_UNMAPPED_DERIVED_STATES: &[&str] = &[")
        for state in UNMAPPED_DERIVED_MOTION_STATES:
            lines.append(f'    "{state}",')
        lines.append("];")
    else:
        lines.append("pub(crate) const FALCON_ECB_UNMAPPED_DERIVED_STATES: &[&str] = &[];")
    lines.append("")

    return "\n".join(lines)


def build_coverage_payload(samples: dict[str, Any]) -> dict[str, Any]:
    actions = {
        int(action["action_state_id"]): action
        for action in samples.get("actions", [])
        if isinstance(action, dict)
    }
    mapped = []
    missing = []
    for state, action_id in MOTION_STATE_ACTION_MAP:
        action = actions.get(action_id)
        if action is None:
            missing.append({"motion_state": state, "action_state_id": action_id})
            continue
        mapped.append(
            {
                "motion_state": state,
                "action_state_id": action_id,
                "source_action": action.get("name") or action.get("figatree_root"),
                "sample_frames": len(action.get("frames", [])),
                "status": "mapped_exact_action_table",
            }
        )

    return {
        "id": "falcon_ecb_coverage",
        "title": "Captain Falcon ECB Coverage",
        "source": {
            "samples": "resources/melee/extracted/captain_falcon_action_ecb_samples.json",
            "generated_rust": "crates/mole_core/src/generated/falcon_ecb.rs",
        },
        "mapped_motion_state_count": len(mapped),
        "mapped_action_count": len({row["action_state_id"] for row in mapped}),
        "missing_sampled_mappings": missing,
        "unmapped_derived_motion_states": list(UNMAPPED_DERIVED_MOTION_STATES),
        "mapped_motion_states": mapped,
    }


def render_ecb(frame: dict[str, Any]) -> str:
    return (
        "EcbDiamond { "
        f"top: {render_vec(frame['top_milli'])}, "
        f"right: {render_vec(frame['right_milli'])}, "
        f"bottom: {render_vec(frame['bottom_milli'])}, "
        f"left: {render_vec(frame['left_milli'])} "
        "}"
    )


def render_vec(point: dict[str, Any]) -> str:
    return f"Vec2 {{ x: {int(point['x'])}, y: {int(point['y'])} }}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--coverage-json", type=Path, default=DEFAULT_COVERAGE_JSON)
    args = parser.parse_args()

    samples = json.loads(args.input.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_generated_rust(samples), encoding="utf-8")
    subprocess.run(["rustfmt", str(args.output)], check=True)
    print(args.output)
    if args.coverage_json is not None:
        args.coverage_json.parent.mkdir(parents=True, exist_ok=True)
        args.coverage_json.write_text(
            json.dumps(build_coverage_payload(samples), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print(args.coverage_json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
