"""Generate Rust Falcon ECB tables from extracted Melee action samples."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any

try:
    from tools.extract_melee_resources import (
        extract_character_action_animation_table,
        extract_character_costume_skeleton_from_dat,
        extract_character_ecb_source_from_dat,
        extract_character_profile_from_dat,
        extract_figatree_summary,
        action_anim_flags_clear_transn_after_sampling,
        character_resource_spec,
        read_u32,
        source_transn_joint_index_from_skeleton,
    )
    from tools.falcon_ecb_mapping import (
        CANONICAL_SOURCE_ONLY_ACTION_MAP,
        FALCON_SPECIAL_ACTION_BINDINGS,
        MOTION_STATE_ACTION_MAP,
        UNMAPPED_DERIVED_MOTION_STATES,
        sampled_action_ids,
    )
    from tools.rust_literals import render_f32_bits
except ModuleNotFoundError:  # pragma: no cover - direct script execution path
    from extract_melee_resources import (  # type: ignore
        extract_character_action_animation_table,
        extract_character_costume_skeleton_from_dat,
        extract_character_ecb_source_from_dat,
        extract_character_profile_from_dat,
        extract_figatree_summary,
        action_anim_flags_clear_transn_after_sampling,
        character_resource_spec,
        read_u32,
        source_transn_joint_index_from_skeleton,
    )
    from falcon_ecb_mapping import (  # type: ignore
        CANONICAL_SOURCE_ONLY_ACTION_MAP,
        FALCON_SPECIAL_ACTION_BINDINGS,
        MOTION_STATE_ACTION_MAP,
        UNMAPPED_DERIVED_MOTION_STATES,
        sampled_action_ids,
    )
    from rust_literals import render_f32_bits  # type: ignore

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = PROJECT_ROOT / "resources" / "melee" / "extracted" / "captain_falcon_action_ecb_samples.json"
DEFAULT_OUTPUT = PROJECT_ROOT / "crates" / "mole_core" / "src" / "generated" / "falcon_ecb.rs"
DEFAULT_COVERAGE_JSON = PROJECT_ROOT / "docs" / "state_graphs" / "parity_reports" / "falcon_ecb_coverage.json"
DEFAULT_RAW_DIR = PROJECT_ROOT / "resources" / "melee" / "raw"


def render_generated_rust(samples: dict[str, Any]) -> str:
    actions = {
        int(action["action_state_id"]): action
        for action in samples.get("actions", [])
        if isinstance(action, dict)
    }
    mapped_action_ids = [
        action_id for action_id in sampled_action_ids() if action_id in actions
    ]

    lines: list[str] = [
        "// @generated by tools/generate_falcon_ecb_rust.py; do not edit by hand.",
        "use super::{MotionState, SourceFighterEcb, SourceVec2, Vec2};",
        "use crate::collision::EcbDiamond;",
        "",
        "#[allow(dead_code)]",
        f"pub(crate) const FALCON_ECB_MAPPED_ACTION_COUNT: usize = {len(mapped_action_ids)};",
        "",
    ]

    for action_id in mapped_action_ids:
        action = actions[action_id]
        frames = action.get("frames", [])
        source_name = str(action.get("name") or action.get("figatree_root") or "")
        lines.append(f"// action {action_id}: {source_name}")
        lines.append("#[allow(dead_code)]")
        lines.append(
            f"const FALCON_ECB_ACTION_{action_id}: [EcbDiamond; {len(frames)}] = ["
        )
        for frame in frames:
            lines.append(f"    {render_ecb(frame)},")
        lines.append("];")
        lines.append("")
        lines.append(
            f"const FALCON_SOURCE_ECB_ACTION_{action_id}: [SourceFighterEcb; {len(frames)}] = ["
        )
        for frame in frames:
            lines.append(f"    {render_source_ecb(frame)},")
        lines.append("];")
        lines.append("")

    live_payload = build_live_jobj_payload(mapped_action_ids)
    if live_payload is not None:
        lines.extend(render_live_jobj_payload(live_payload))

    lines.append("pub(crate) fn falcon_ecb_samples_for_motion_state(")
    lines.append("    motion_state: MotionState,")
    lines.append(") -> Option<&'static [EcbDiamond]> {")
    lines.append("    match motion_state {")
    for state, action_id in MOTION_STATE_ACTION_MAP:
        if action_id in actions:
            lines.append(
                f"        MotionState::{state} => Some(&FALCON_ECB_ACTION_{action_id}),"
            )
    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    if live_payload is not None:
        lines.append("pub(crate) fn falcon_source_ecb_jobj_for_motion_state(")
        lines.append("    motion_state: MotionState,")
        lines.append("    pose_frame_milli: i32,")
        lines.append(") -> Option<SourceFighterEcb> {")
        lines.append("    let action = match motion_state {")
        for state, action_id in MOTION_STATE_ACTION_MAP:
            if action_id in actions and action_id in live_payload["actions"]:
                lines.append(
                    f"        MotionState::{state} => &FALCON_FIGA_ACTION_{action_id},"
                )
        lines.append("        _ => return None,")
        lines.append("    };")
        lines.append("    falcon_eval_source_ecb_from_jobj(action, pose_frame_milli)")
        lines.append("}")
        lines.append("")
        lines.append("pub(crate) fn falcon_source_ecb_jobj_for_action_table_id(")
        lines.append("    source_action_table_id: u16,")
        lines.append("    pose_frame_milli: i32,")
        lines.append(") -> Option<SourceFighterEcb> {")
        lines.append("    let action = match source_action_table_id {")
        for action_id in source_action_table_ids():
            if action_id in actions and action_id in live_payload["actions"]:
                lines.append(f"        {action_id} => &FALCON_FIGA_ACTION_{action_id},")
        lines.append("        _ => return None,")
        lines.append("    };")
        lines.append("    falcon_eval_source_ecb_from_jobj(action, pose_frame_milli)")
        lines.append("}")
        lines.append("")
    lines.append("pub(crate) fn falcon_source_ecb_samples_for_motion_state(")
    lines.append("    motion_state: MotionState,")
    lines.append(") -> Option<&'static [SourceFighterEcb]> {")
    lines.append("    match motion_state {")
    for state, action_id in MOTION_STATE_ACTION_MAP:
        if action_id in actions:
            lines.append(
                f"        MotionState::{state} => Some(&FALCON_SOURCE_ECB_ACTION_{action_id}),"
            )
    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("pub(crate) fn falcon_source_ecb_samples_for_action_table_id(")
    lines.append("    source_action_table_id: u16,")
    lines.append(") -> Option<&'static [SourceFighterEcb]> {")
    lines.append("    match source_action_table_id {")
    for action_id in source_action_table_ids():
        if action_id in actions:
            lines.append(f"        {action_id} => Some(&FALCON_SOURCE_ECB_ACTION_{action_id}),")
    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#[allow(dead_code)]")
    if UNMAPPED_DERIVED_MOTION_STATES:
        lines.append("pub(crate) const FALCON_ECB_UNMAPPED_DERIVED_STATES: &[&str] = &[")
        for state in UNMAPPED_DERIVED_MOTION_STATES:
            lines.append(f'    "{state}",')
        lines.append("];")
    else:
        lines.append("pub(crate) const FALCON_ECB_UNMAPPED_DERIVED_STATES: &[&str] = &[];")
    lines.append("")

    return "\n".join(lines)


def source_action_table_ids() -> tuple[int, ...]:
    return tuple(
        dict.fromkeys(
            [
                *(action_id for _runtime_id, action_id, _key in CANONICAL_SOURCE_ONLY_ACTION_MAP),
                *(
                    action_id
                    for _state, _runtime_id, action_id, _key, _frames in FALCON_SPECIAL_ACTION_BINDINGS
                ),
            ]
        )
    )


def build_live_jobj_payload(mapped_action_ids: list[int]) -> dict[str, Any] | None:
    raw_dir = DEFAULT_RAW_DIR
    plca = raw_dir / "PlCa.dat"
    plcaaj = raw_dir / "PlCaAJ.dat"
    plcanr = raw_dir / "PlCaNr.dat"
    if not (plca.exists() and plcaaj.exists() and plcanr.exists()):
        return None

    spec = character_resource_spec("captain")
    fighter_bytes = plca.read_bytes()
    action_bytes = plcaaj.read_bytes()
    skeleton = extract_character_costume_skeleton_from_dat(plcanr.read_bytes(), plcanr, spec)
    action_table = extract_character_action_animation_table(
        fighter_bytes, plca, action_bytes, plcaaj, spec
    )
    ecb_source = extract_character_ecb_source_from_dat(fighter_bytes, plca, spec)["ecb_source"]
    profile = extract_character_profile_from_dat(fighter_bytes, plca, spec)
    model_scaling = float(profile["fields"]["model_scaling"]["raw"])
    actions_by_id = {
        int(action["action_state_id"]): action
        for action in action_table["actions"]
        if isinstance(action, dict)
    }

    live_actions: dict[int, dict[str, Any]] = {}
    for action_id in mapped_action_ids:
        action = actions_by_id.get(action_id)
        if action is None or not isinstance(action.get("figatree"), dict):
            continue
        offset = int(action["figatree_archive_offset"])
        size = int(action["figatree_archive_size"])
        chunk = action_bytes[offset : offset + size]
        summary = extract_figatree_summary(chunk)
        tracks = []
        for track in summary["tracks"]:
            if not isinstance(track, dict):
                continue
            data_offset = int(track["data_offset"])
            length = int(track["length"])
            frac_value = int(str(track["frac_value_raw"]), 16)
            frac_slope = int(str(track["frac_slope_raw"]), 16)
            data_start = 0x20 + data_offset
            payload_end = fobj_declared_length_payload_end(
                chunk[data_start:],
                length=length,
                frac_value=frac_value,
                frac_slope=frac_slope,
            )
            tracks.append(
                {
                    "node_index": node_index_for_track(summary, int(track["index"])),
                    "obj_type": int(track["obj_type"]),
                    "startframe": int(track["startframe"]),
                    "frac_value": frac_value,
                    "frac_slope": frac_slope,
                    "length": length,
                    "data": list(chunk[data_start : data_start + payload_end]),
                }
            )
        live_actions[action_id] = {
            "clear_transn_after_anim": action_anim_flags_clear_transn_after_sampling(
                int(str(action.get("flags_raw", "0x00000000")), 16)
            ),
            "frames_ticks": int(action["figatree"]["frames_ticks"]),
            "track_counts_by_node": [int(value) for value in summary["track_counts_by_node"]],
            "tracks": tracks,
        }

    return {
        "joints": skeleton["joints"],
        "ecb_source": ecb_source,
        "model_scaling": model_scaling,
        "transn_joint_index": source_transn_joint_index_from_skeleton(skeleton),
        "actions": live_actions,
    }


def node_index_for_track(summary: dict[str, Any], track_index: int) -> int:
    cursor = 0
    for node_index, count in enumerate(summary["track_counts_by_node"]):
        next_cursor = cursor + int(count)
        if cursor <= track_index < next_cursor:
            return node_index
        cursor = next_cursor
    raise ValueError(f"track index {track_index} is outside the FigaTree node table")


def fobj_frac_byte_width(frac: int) -> int:
    if frac == 0:
        return 4
    frac_kind = frac & 0xE0
    if frac_kind in (0x60, 0x80):
        return 1
    if frac_kind in (0x20, 0x40):
        return 2
    raise ValueError(f"unsupported FObj fraction byte 0x{frac:02x}")


def scan_fobj_pack_info(data: bytes, pos: int) -> tuple[int, int]:
    if pos >= len(data):
        raise ValueError("FObj animation data ended before packet header")
    d = data[pos]
    pos += 1
    nb_pack = ((d >> 4) & 7) + 1
    shift = 3
    while d & 0x80:
        if pos >= len(data):
            raise ValueError("FObj animation data ended mid-packet header")
        d = data[pos]
        pos += 1
        nb_pack += (d & 0x7F) << shift
        shift += 7
    return nb_pack, pos


def scan_fobj_wait(data: bytes, pos: int) -> tuple[int, int]:
    value = 0
    shift = 0
    while True:
        if pos >= len(data):
            raise ValueError("FObj animation data ended mid-wait")
        d = data[pos]
        pos += 1
        value += (d & 0x7F) << shift
        if d & 0x80 == 0:
            return value, pos
        shift += 7


def fobj_declared_length_payload_end(
    data: bytes,
    *,
    length: int,
    frac_value: int,
    frac_slope: int,
) -> int:
    """Return bytes reachable when HSD gates token starts by declared length."""

    pos = 0
    max_pos = 0
    state = 1
    nb_pack = 0
    op = 0
    while True:
        if state in (1, 2):
            if pos >= length:
                return max(max_pos, min(pos, len(data)))
            if nb_pack == 0:
                if pos >= len(data):
                    raise ValueError("FObj animation data ended before packet header")
                op = data[pos] & 0x0F
                nb_pack, pos = scan_fobj_pack_info(data, pos)
                max_pos = max(max_pos, pos)
            nb_pack -= 1

            if op in (1, 2, 3, 6):
                pos += fobj_frac_byte_width(frac_value)
                state = 3
            elif op == 4:
                pos += fobj_frac_byte_width(frac_value)
                pos += fobj_frac_byte_width(frac_slope)
                state = 3
            elif op == 5:
                pos += fobj_frac_byte_width(frac_slope)
            else:
                raise ValueError(f"unsupported FObj op {op}")
            if pos > len(data):
                raise ValueError("FObj animation data ended mid-token")
            max_pos = max(max_pos, pos)
            continue

        if state == 3:
            if pos >= length:
                return max(max_pos, min(pos, len(data)))
            _, pos = scan_fobj_wait(data, pos)
            max_pos = max(max_pos, pos)
            state = 2
            continue

        raise ValueError(f"unsupported FObj scan state {state}")


def render_live_jobj_payload(payload: dict[str, Any]) -> list[str]:
    lines: list[str] = [
        "#[derive(Clone, Copy)]",
        "struct FalconSourceJoint {",
        "    parent: i16,",
        "    flags: u32,",
        "    rotation: SourceVec3Gen,",
        "    scale: SourceVec3Gen,",
        "    translation: SourceVec3Gen,",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "struct FalconFigaTrack {",
        "    node_index: usize,",
        "    obj_type: u8,",
        "    startframe: u16,",
        "    frac_value: u8,",
        "    frac_slope: u8,",
        "    length: u16,",
        "    data: &'static [u8],",
        "}",
        "",
        "struct FalconFigaAction {",
        "    clear_transn_after_anim: bool,",
        "    tracks: &'static [FalconFigaTrack],",
        "}",
        "",
        "#[derive(Clone, Copy, Default)]",
        "struct SourceVec3Gen {",
        "    x: f32,",
        "    y: f32,",
        "    z: f32,",
        "}",
        "",
        "#[derive(Clone, Copy, Default)]",
        "struct SourceSrt {",
        "    rotation: SourceVec3Gen,",
        "    scale: SourceVec3Gen,",
        "    translation: SourceVec3Gen,",
        "}",
        "",
        "#[derive(Clone, Copy, Default)]",
        "struct SourceMatrix {",
        "    m: [[f32; 4]; 3],",
        "}",
        "",
        "const FALCON_TOPN_COLLISION_ROT_Y: f32 = core::f32::consts::FRAC_PI_2;",
        f"const FALCON_MODEL_SCALE: f32 = {render_f32(payload['model_scaling'])};",
        "const FALCON_TOPN_COLLISION_SCALE: SourceVec3Gen = SourceVec3Gen {",
        "    x: FALCON_MODEL_SCALE,",
        "    y: FALCON_MODEL_SCALE,",
        "    z: FALCON_MODEL_SCALE,",
        "};",
        f"const FALCON_TRANSN_JOINT_INDEX: usize = {int(payload['transn_joint_index'])};",
        f"const FALCON_ECB_SOURCE_JOINTS: [usize; 6] = {render_usize_array(payload['ecb_source']['joint_indices'])};",
        f"const FALCON_ECB_SIDE_MIDPOINT_OFFSET: f32 = {render_f32(payload['ecb_source']['side_midpoint_offset_raw'])};",
        f"const FALCON_SOURCE_JOINTS: [FalconSourceJoint; {len(payload['joints'])}] = [",
    ]
    for joint in payload["joints"]:
        parent = joint.get("parent_index")
        lines.append(
            "    FalconSourceJoint { "
            f"parent: {int(parent) if parent is not None else -1}, "
            f"flags: {int(str(joint['flags_raw']), 16)}, "
            f"rotation: {render_vec3_gen(joint['rotation_raw'])}, "
            f"scale: {render_vec3_gen(joint['scale_raw'])}, "
            f"translation: {render_vec3_gen(joint['position_raw'])} "
            "},"
        )
    lines.append("];")
    lines.append("")

    for action_id, action in sorted(payload["actions"].items()):
        lines.append(
            f"const FALCON_FIGA_TRACKS_ACTION_{action_id}: [FalconFigaTrack; {len(action['tracks'])}] = ["
        )
        for track in action["tracks"]:
            lines.append(
                "    FalconFigaTrack { "
                f"node_index: {track['node_index']}, "
                f"obj_type: {track['obj_type']}, "
                f"startframe: {track['startframe']}, "
                f"frac_value: 0x{track['frac_value']:02x}, "
                f"frac_slope: 0x{track['frac_slope']:02x}, "
                f"length: {track['length']}, "
                f"data: {render_u8_slice(track['data'])} "
                "},"
            )
        lines.append("];")
        clear_transn_after_anim = (
            "true" if bool(action.get("clear_transn_after_anim")) else "false"
        )
        lines.append(
            f"const FALCON_FIGA_ACTION_{action_id}: FalconFigaAction = FalconFigaAction {{ "
            f"clear_transn_after_anim: {clear_transn_after_anim}, "
            f"tracks: &FALCON_FIGA_TRACKS_ACTION_{action_id} "
            "};"
        )
        lines.append("")

    lines.extend(render_live_jobj_evaluator())
    return lines


def render_vec3_gen(point: dict[str, Any]) -> str:
    return (
        "SourceVec3Gen { "
        f"x: {render_f32(point['x'])}, "
        f"y: {render_f32(point['y'])}, "
        f"z: {render_f32(point['z'])} "
        "}"
    )


def render_usize_array(values: Any) -> str:
    return "[" + ", ".join(str(int(value)) for value in values) + "]"


def render_u8_slice(values: list[int]) -> str:
    return "&[" + ", ".join(f"0x{int(value):02x}" for value in values) + "]"


def render_live_jobj_evaluator() -> list[str]:
    return [
        "fn falcon_eval_source_ecb_from_jobj(",
        "    action: &FalconFigaAction,",
        "    pose_frame_milli: i32,",
        ") -> Option<SourceFighterEcb> {",
        "    let frame = pose_frame_milli.max(0) as f32 / 1000.0;",
        "    let mut srts = [SourceSrt::default(); FALCON_SOURCE_JOINTS.len()];",
        "    for (index, joint) in FALCON_SOURCE_JOINTS.iter().enumerate() {",
        "        srts[index] = SourceSrt {",
        "            rotation: joint.rotation,",
        "            scale: joint.scale,",
        "            translation: joint.translation,",
        "        };",
        "    }",
        "    srts[0].rotation.y = FALCON_TOPN_COLLISION_ROT_Y;",
        "    srts[0].scale = FALCON_TOPN_COLLISION_SCALE;",
        "    for track in action.tracks {",
        "        let value = falcon_sample_fobj_value(track, frame)?;",
        "        let srt = srts.get_mut(track.node_index)?;",
        "        match track.obj_type {",
        "            1 => srt.rotation.x = value,",
        "            2 => srt.rotation.y = value,",
        "            3 => srt.rotation.z = value,",
        "            5 => srt.translation.x = value,",
        "            6 => srt.translation.y = value,",
        "            7 => srt.translation.z = value,",
        "            8 => srt.scale.x = value,",
        "            9 => srt.scale.y = value,",
        "            10 => srt.scale.z = value,",
        "            _ => {}",
        "        }",
        "    }",
        "    if action.clear_transn_after_anim {",
        "        srts[FALCON_TRANSN_JOINT_INDEX].translation = SourceVec3Gen::default();",
        "    }",
        "    let matrices = falcon_eval_joint_matrices(&srts);",
        "    let mut left_x = f32::INFINITY;",
        "    let mut right_x = f32::NEG_INFINITY;",
        "    let mut bottom_y = f32::INFINITY;",
        "    let mut top_y = f32::NEG_INFINITY;",
        "    for joint_index in FALCON_ECB_SOURCE_JOINTS {",
        "        let pos = matrices[joint_index].translation();",
        "        left_x = left_x.min(pos.x);",
        "        right_x = right_x.max(pos.x);",
        "        bottom_y = bottom_y.min(pos.y);",
        "        top_y = top_y.max(pos.y);",
        "    }",
        "    let width = (right_x - left_x).abs();",
        "    if width < 10.0 {",
        "        right_x = 0.5 * width;",
        "        left_x = -right_x;",
        "    }",
        "    let height = (top_y - bottom_y).abs();",
        "    if height < 10.0 {",
        "        let half_height = 0.5 * height;",
        "        let mid_y = 0.5 * (top_y + bottom_y);",
        "        top_y = mid_y + half_height;",
        "        bottom_y = mid_y - half_height;",
        "    }",
        "    right_x = if right_x < 2.0 { 2.0 } else { right_x };",
        "    left_x = if left_x > -2.0 { -2.0 } else { left_x };",
        "    if bottom_y < 0.0 { bottom_y = 0.0; }",
        "    let midpoint_y = FALCON_ECB_SIDE_MIDPOINT_OFFSET + 0.5 * (bottom_y + top_y);",
        "    Some(SourceFighterEcb {",
        "        top: SourceVec2 { x: 0.0, y: top_y },",
        "        right: SourceVec2 { x: right_x, y: midpoint_y },",
        "        bottom: SourceVec2 { x: 0.0, y: bottom_y },",
        "        left: SourceVec2 { x: left_x, y: midpoint_y },",
        "    })",
        "}",
        "",
        "fn falcon_eval_joint_matrices(srts: &[SourceSrt; FALCON_SOURCE_JOINTS.len()]) -> [SourceMatrix; FALCON_SOURCE_JOINTS.len()] {",
        "    let mut matrices = [SourceMatrix::default(); FALCON_SOURCE_JOINTS.len()];",
        "    let mut global_scales = [SourceVec3Gen::default(); FALCON_SOURCE_JOINTS.len()];",
        "    for (index, joint) in FALCON_SOURCE_JOINTS.iter().enumerate() {",
        "        let parent = if joint.parent >= 0 { Some(joint.parent as usize) } else { None };",
        "        let parent_scale = parent.map(|parent_index| global_scales[parent_index]);",
        "        let local = SourceMatrix::from_srt(srts[index].scale, srts[index].rotation, srts[index].translation, parent_scale);",
        "        matrices[index] = if let Some(parent_index) = parent { matrices[parent_index].concat(local) } else { local };",
        "        global_scales[index] = if joint.flags & 8 != 0 {",
        "            parent_scale.unwrap_or(srts[index].scale)",
        "        } else if let Some(parent_scale) = parent_scale {",
        "            SourceVec3Gen {",
        "                x: srts[index].scale.x * parent_scale.x,",
        "                y: srts[index].scale.y * parent_scale.y,",
        "                z: srts[index].scale.z * parent_scale.z,",
        "            }",
        "        } else {",
        "            srts[index].scale",
        "        };",
        "    }",
        "    matrices",
        "}",
        "",
        "impl SourceMatrix {",
        "    fn from_srt(scale: SourceVec3Gen, rotation: SourceVec3Gen, translation: SourceVec3Gen, parent_scale: Option<SourceVec3Gen>) -> Self {",
        "        let (sin_x, cos_x) = rotation.x.sin_cos();",
        "        let (sin_y, cos_y) = rotation.y.sin_cos();",
        "        let (sin_z, cos_z) = rotation.z.sin_cos();",
        "        let scale_x2 = scale.x;",
        "        let mut scale_x1 = scale.x;",
        "        let mut scale_x = scale.x;",
        "        let mut scale_y = scale.y;",
        "        let scale_y1 = scale.y;",
        "        let mut scale_y2 = scale.y;",
        "        let mut scale_z1 = scale.z;",
        "        let mut scale_z2 = scale.z;",
        "        let scale_z = scale.z;",
        "        if let Some(parent_scale) = parent_scale {",
        "            let temp1 = 1.0 / parent_scale.x;",
        "            let temp2 = 1.0 / parent_scale.y;",
        "            let temp3 = 1.0 / parent_scale.z;",
        "            scale_y2 *= parent_scale.y * temp1;",
        "            scale_z2 *= parent_scale.z * temp1;",
        "            scale_x1 *= parent_scale.x * temp2;",
        "            scale_z1 *= parent_scale.z * temp2;",
        "            scale_x *= parent_scale.x * temp3;",
        "            scale_y *= parent_scale.y * temp3;",
        "        }",
        "        let m00 = cos_z * (scale_x2 * cos_y);",
        "        let m01 = scale_y2 * ((cos_z * (sin_x * sin_y)) - (cos_x * sin_z));",
        "        let m02 = scale_z2 * ((cos_z * (cos_x * sin_y)) + (sin_x * sin_z));",
        "        let m10 = sin_z * (scale_x1 * cos_y);",
        "        let m11 = scale_y1 * ((sin_z * (sin_x * sin_y)) + (cos_x * cos_z));",
        "        let m12 = scale_z1 * ((sin_z * (cos_x * sin_y)) - (sin_x * cos_z));",
        "        let m20 = -scale_x * sin_y;",
        "        let m21 = cos_y * (scale_y * sin_x);",
        "        let m22 = cos_y * (scale_z * cos_x);",
        "        Self { m: [[m00, m01, m02, translation.x], [m10, m11, m12, translation.y], [m20, m21, m22, translation.z]] }",
        "    }",
        "",
        "    fn concat(self, child: Self) -> Self {",
        "        let mut out = SourceMatrix::default();",
        "        for row in 0..3 {",
        "            for col in 0..3 {",
        "                out.m[row][col] = self.m[row][0] * child.m[0][col] + self.m[row][1] * child.m[1][col] + self.m[row][2] * child.m[2][col];",
        "            }",
        "            out.m[row][3] = self.m[row][0] * child.m[0][3] + self.m[row][1] * child.m[1][3] + self.m[row][2] * child.m[2][3] + self.m[row][3];",
        "        }",
        "        out",
        "    }",
        "",
        "    fn translation(self) -> SourceVec3Gen {",
        "        SourceVec3Gen { x: self.m[0][3], y: self.m[1][3], z: self.m[2][3] }",
        "    }",
        "}",
        "",
        "fn falcon_sample_fobj_value(track: &FalconFigaTrack, frame: f32) -> Option<f32> {",
        "    const HSD_A_OP_CON: u8 = 1;",
        "    const HSD_A_OP_LIN: u8 = 2;",
        "    const HSD_A_OP_SPL0: u8 = 3;",
        "    const HSD_A_OP_SPL: u8 = 4;",
        "    const HSD_A_OP_SLP: u8 = 5;",
        "    const HSD_A_OP_KEY: u8 = 6;",
        "    let data = track.data;",
        "    let mut pos = 0usize;",
        "    let mut time = track.startframe as f32 + frame;",
        "    let mut flags = 0u8;",
        "    let mut state = 1u8;",
        "    let mut op = 0u8;",
        "    let mut op_intrp = 0u8;",
        "    let mut nb_pack = 0usize;",
        "    let mut fterm = 0i32;",
        "    let mut p0 = 0.0f32;",
        "    let mut p1 = 0.0f32;",
        "    let mut d0 = 0.0f32;",
        "    let mut d1 = 0.0f32;",
        "    let mut carried_fterm = 0.0f32;",
        "    let mut last_value = None;",
        "    loop {",
        "        match state {",
        "            1 | 2 => {",
        "                if pos >= track.length as usize { state = 6; continue; }",
        "                let load_state = state;",
        "                op_intrp = op;",
        "                if nb_pack == 0 {",
        "                    op = data[pos] & 0x0F;",
        "                    let parsed = parse_fobj_pack_info(data, pos)?;",
        "                    nb_pack = parsed.0;",
        "                    pos = parsed.1;",
        "                }",
        "                nb_pack = nb_pack.saturating_sub(1);",
        "                match op {",
        "                    HSD_A_OP_CON | HSD_A_OP_LIN => { p0 = p1; let parsed = parse_fobj_float(data, pos, track.frac_value)?; p1 = parsed.0; pos = parsed.1; if op_intrp != HSD_A_OP_SLP { d0 = d1; d1 = 0.0; } }",
        "                    HSD_A_OP_SPL0 => { p0 = p1; d0 = d1; let parsed = parse_fobj_float(data, pos, track.frac_value)?; p1 = parsed.0; pos = parsed.1; d1 = 0.0; }",
        "                    HSD_A_OP_SPL => { p0 = p1; let parsed = parse_fobj_float(data, pos, track.frac_value)?; p1 = parsed.0; pos = parsed.1; d0 = d1; let parsed = parse_fobj_float(data, pos, track.frac_slope)?; d1 = parsed.0; pos = parsed.1; }",
        "                    HSD_A_OP_SLP => { d0 = d1; let parsed = parse_fobj_float(data, pos, track.frac_slope)?; d1 = parsed.0; pos = parsed.1; }",
        "                    HSD_A_OP_KEY => { launch_fobj_key_data(&mut flags, op, &mut op_intrp, &mut p0, p1); let parsed = parse_fobj_float(data, pos, track.frac_value)?; p1 = parsed.0; pos = parsed.1; flags |= 0x40; }",
        "                    _ => return None,",
        "                }",
        "                state = if op == HSD_A_OP_SLP { load_state } else if load_state == 1 { 3 } else { 4 };",
        "            }",
        "            3 => {",
        "                if flags & 0x80 != 0 { if let Some(value) = update_fobj_anim(op_intrp, &mut flags, fterm, time, p0, p1, &mut d0, d1) { last_value = Some(value); } }",
        "                if pos >= track.length as usize { state = 6; } else { let parsed = parse_fobj_wait(data, pos)?; fterm = parsed.0; pos = parsed.1; flags |= 0x20; state = 2; }",
        "            }",
        "            4 => {",
        "                if (fterm as f32) <= time { carried_fterm = fterm as f32; time -= fterm as f32; state = 3; continue; }",
        "                if let Some(value) = update_fobj_anim(op_intrp, &mut flags, fterm, time, p0, p1, &mut d0, d1) { return Some(value); }",
        "                state = 5;",
        "            }",
        "            5 => state = 4,",
        "            6 => {",
        "                time += carried_fterm;",
        "                launch_fobj_key_data(&mut flags, op, &mut op_intrp, &mut p0, p1);",
        "                if let Some(value) = update_fobj_anim(op_intrp, &mut flags, fterm, time, p0, p1, &mut d0, d1) { return Some(value); }",
        "                return last_value;",
        "            }",
        "            _ => return last_value,",
        "        }",
        "    }",
        "}",
        "",
        "fn launch_fobj_key_data(flags: &mut u8, op: u8, op_intrp: &mut u8, p0: &mut f32, p1: f32) {",
        "    if *flags & 0x40 != 0 {",
        "        *op_intrp = op;",
        "        *flags &= !0x40;",
        "        *flags |= 0x80;",
        "        *p0 = p1;",
        "    }",
        "}",
        "",
        "fn update_fobj_anim(op_intrp: u8, flags: &mut u8, fterm: i32, time: f32, mut p0: f32, p1: f32, d0: &mut f32, d1: f32) -> Option<f32> {",
        "    match op_intrp {",
        "        6 => { if *flags & 0x80 != 0 { *flags &= !0x80; Some(p0) } else { None } }",
        "        1 => Some(if time >= fterm as f32 { p1 } else { p0 }),",
        "        2 => { if *flags & 0x20 != 0 { *flags &= !0x20; if fterm != 0 { *d0 = (p1 - p0) / fterm as f32; } else { *d0 = 0.0; p0 = p1; } } Some(*d0 * time + p0) }",
        "        3 | 4 | 5 => { if fterm != 0 { Some(spl_get_hermite(1.0 / fterm as f32, time, p0, p1, *d0, d1)) } else { Some(p1) } }",
        "        _ => None,",
        "    }",
        "}",
        "",
        "fn spl_get_hermite(inv_fterm: f32, time: f32, p0: f32, p1: f32, d0: f32, d1: f32) -> f32 {",
        "    let time_sq = time * time;",
        "    let inv_sq = inv_fterm * inv_fterm;",
        "    let time_sq_inv = time_sq * inv_fterm;",
        "    let inv_sq_time_cu = inv_sq * (time_sq * time);",
        "    let two_time_cu_inv_cu = 2.0 * inv_sq_time_cu * inv_fterm;",
        "    let three_time_sq_inv_sq = 3.0 * time_sq * inv_sq;",
        "    d1 * (inv_sq_time_cu - time_sq_inv) + d0 * (time + ((inv_sq_time_cu - time_sq_inv) - time_sq_inv)) + p0 * (1.0 + (two_time_cu_inv_cu - three_time_sq_inv_sq)) + p1 * (-two_time_cu_inv_cu + three_time_sq_inv_sq)",
        "}",
        "",
        "fn parse_fobj_pack_info(data: &[u8], mut pos: usize) -> Option<(usize, usize)> {",
        "    let mut d = *data.get(pos)?;",
        "    pos += 1;",
        "    let mut nb_pack = ((d >> 4) & 7) as usize + 1;",
        "    let mut shift = 3usize;",
        "    while d & 0x80 != 0 {",
        "        d = *data.get(pos)?;",
        "        pos += 1;",
        "        nb_pack += ((d & 0x7F) as usize) << shift;",
        "        shift += 7;",
        "    }",
        "    Some((nb_pack, pos))",
        "}",
        "",
        "fn parse_fobj_wait(data: &[u8], mut pos: usize) -> Option<(i32, usize)> {",
        "    let mut wait = 0i32;",
        "    let mut shift = 0;",
        "    loop {",
        "        let d = *data.get(pos)?;",
        "        pos += 1;",
        "        wait |= ((d & 0x7F) as i32) << shift;",
        "        shift += 7;",
        "        if d & 0x80 == 0 { return Some((wait, pos)); }",
        "    }",
        "}",
        "",
        "fn parse_fobj_float(data: &[u8], pos: usize, frac: u8) -> Option<(f32, usize)> {",
        "    if frac == 0 {",
        "        let bytes: [u8; 4] = data.get(pos..pos + 4)?.try_into().ok()?;",
        "        return Some((f32::from_le_bytes(bytes), pos + 4));",
        "    }",
        "    let denom = (1u32 << (frac & 0x1F)) as f32;",
        "    match frac & 0xE0 {",
        "        0x60 => Some((*data.get(pos)? as i8 as f32 / denom, pos + 1)),",
        "        0x80 => Some((*data.get(pos)? as f32 / denom, pos + 1)),",
        "        0x20 => { let bytes: [u8; 2] = data.get(pos..pos + 2)?.try_into().ok()?; Some((i16::from_le_bytes(bytes) as f32 / denom, pos + 2)) }",
        "        0x40 => { let bytes: [u8; 2] = data.get(pos..pos + 2)?.try_into().ok()?; Some((u16::from_le_bytes(bytes) as f32 / denom, pos + 2)) }",
        "        _ => None,",
        "    }",
        "}",
        "",
    ]


def build_coverage_payload(samples: dict[str, Any]) -> dict[str, Any]:
    actions = {
        int(action["action_state_id"]): action
        for action in samples.get("actions", [])
        if isinstance(action, dict)
    }
    mapped = []
    missing = []
    for state, action_id in MOTION_STATE_ACTION_MAP:
        action = actions.get(action_id)
        if action is None:
            missing.append({"motion_state": state, "action_state_id": action_id})
            continue
        mapped.append(
            {
                "motion_state": state,
                "action_state_id": action_id,
                "source_action": action.get("name") or action.get("figatree_root"),
                "sample_frames": len(action.get("frames", [])),
                "status": "mapped_exact_action_table",
            }
        )

    return {
        "id": "falcon_ecb_coverage",
        "title": "Captain Falcon ECB Coverage",
        "source": {
            "samples": "resources/melee/extracted/captain_falcon_action_ecb_samples.json",
            "generated_rust": "crates/mole_core/src/generated/falcon_ecb.rs",
        },
        "mapped_motion_state_count": len(mapped),
        "mapped_action_count": len({row["action_state_id"] for row in mapped}),
        "missing_sampled_mappings": missing,
        "special_action_bindings": [
            {
                "motion_state": motion_state,
                "runtime_action_state_id": runtime_action_state_id,
                "source_action_table_id": source_action_table_id,
                "source_action_key": source_action_key,
                "total_frames": total_frames,
            }
            for (
                motion_state,
                runtime_action_state_id,
                source_action_table_id,
                source_action_key,
                total_frames,
            ) in FALCON_SPECIAL_ACTION_BINDINGS
        ],
        "unmapped_derived_motion_states": list(UNMAPPED_DERIVED_MOTION_STATES),
        "mapped_motion_states": mapped,
    }


def render_ecb(frame: dict[str, Any]) -> str:
    return (
        "EcbDiamond { "
        f"top: {render_vec(frame['top_milli'])}, "
        f"right: {render_vec(frame['right_milli'])}, "
        f"bottom: {render_vec(frame['bottom_milli'])}, "
        f"left: {render_vec(frame['left_milli'])} "
        "}"
    )


def render_source_ecb(frame: dict[str, Any]) -> str:
    return (
        "SourceFighterEcb { "
        f"top: {render_source_vec(frame['top_raw'])}, "
        f"right: {render_source_vec(frame['right_raw'])}, "
        f"bottom: {render_source_vec(frame['bottom_raw'])}, "
        f"left: {render_source_vec(frame['left_raw'])} "
        "}"
    )


def render_vec(point: dict[str, Any]) -> str:
    return f"Vec2 {{ x: {int(point['x'])}, y: {int(point['y'])} }}"


def render_source_vec(point: dict[str, Any]) -> str:
    return (
        "SourceVec2 { "
        f"x: {render_f32(point['x'])}, "
        f"y: {render_f32(point['y'])} "
        "}"
    )


def render_f32(value: Any) -> str:
    return render_f32_bits(value)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--coverage-json", type=Path, default=DEFAULT_COVERAGE_JSON)
    args = parser.parse_args()

    samples = json.loads(args.input.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_generated_rust(samples), encoding="utf-8")
    subprocess.run(["rustfmt", str(args.output)], check=True)
    print(args.output)
    if args.coverage_json is not None:
        args.coverage_json.parent.mkdir(parents=True, exist_ok=True)
        args.coverage_json.write_text(
            json.dumps(build_coverage_payload(samples), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print(args.coverage_json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
